name: Build Image Editor

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (OpenCV, OpenGL)
        run: |
          sudo apt update
          sudo apt install -y \
            cmake g++ \
            libopencv-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            xorg-dev
          sudo apt install -y libglfw3-dev

      - name: Clone imgui, imnodes, and glfw
        run: |
          mkdir -p lib
          git clone https://github.com/ocornut/imgui.git lib/imgui
          git clone https://github.com/Nelarius/imnodes.git lib/imnodes
          git clone https://github.com/glfw/glfw.git lib/glfw

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --parallel

      - name: Run Executable and Check for Segfault
        run: |
          set +e
          ./build/ImageEditor
          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -eq 139 ]; then
            echo "Segmentation fault detected!"
            exit 1
          elif [ "$EXIT_CODE" -ne 0 ]; then
            echo "Program exited with non-zero code: $EXIT_CODE"
            exit $EXIT_CODE
          else
            echo "Program ran successfully without segmentation fault."
          fi

